name: Build
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:

jobs:
  clang:
    name: Clang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libvulkan-dev mesa-common-dev glslc 

      - name: Install Clang
        uses: egor-tensin/setup-clang@v2
        with:
          version: 21
          platform: x64

      - run: mkdir build

      - name: Generate Buildscripts
        working-directory: build
        run: cmake .. -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++) -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_WAYLAND=OFF -DCMAKE_BUILD_X11=OFF

      - name: Build
        working-directory: build
        run: make
  gcc:
    name: GCC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libvulkan-dev mesa-common-dev glslc 

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v2
        with:
          version: 15
          platform: x64

      - run: mkdir build

      - name: Generate Buildscripts
        working-directory: build
        run: cmake .. -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++) -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_WAYLAND=OFF -DCMAKE_BUILD_X11=OFF

      - name: Build
        working-directory: build
        run: make

  msvc:
    name: "MSVC"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Generate build scripts
        run: |
          mkdir build
          cd build
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..

      - name: Build
        run: |
          cmake --build build
