name: Lint
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:

jobs:
  lint:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install clang

      - name: Run clang-format
        run: find -type f -regextype egrep -regex '^\.\/(src|include)\/(\w*\/)*\w*\.(cpp|h)$' -exec clang-format --dry-run -Werror {} \;
