name: Lint
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:

jobs:
  lint:
    name: clang-format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'include'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check formatting
        uses: jidicula/clang-format-check@v4.18.0
        with:
          clang-format-version: '22'
          check-path: ${{ matrix.path }}
